#!/usr/bin/env python3
import json, sys, os, urllib.request


URLS = [
    # Add (filename, url) tuples here, e.g.:
    # ("account_new1.txt", "https://example.com/cookies/abc_bas.txt"),
]


def json_to_netscape(json_cookies):
    """Convert JSON cookie array to Netscape cookie file format."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by convert_cookies.py", ""]
    for c in json_cookies:
        domain = c.get("domain", "")
        # Only keep youtube/google cookies
        if not any(d in domain for d in [".youtube.com", ".google.com", "google.co"]):
            continue
        # Partitioned cookies: use the domain as-is (yt-dlp needs them)
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0))
        if expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def main():
    for fname, url in URLS:
        print(f"Downloading {fname}...", end=" ", flush=True)
        try:
            req = urllib.request.Request(url, headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
            })
            resp = urllib.request.urlopen(req, timeout=30)
            data = resp.read().decode()
            if not data.strip():
                print("EMPTY")
                continue

            parsed = json.loads(data)
            cookies = parsed.get("cookies", parsed) if isinstance(parsed, dict) else parsed

            netscape = json_to_netscape(cookies)
            out_path = os.path.join(COOKIE_DIR, fname)
            with open(out_path, "w") as f:
                f.write(netscape)

            # Count youtube cookies
            yt_count = sum(1 for line in netscape.split("\n")
                          if ".youtube.com" in line and not line.startswith("#"))
            print(f"OK — {yt_count} youtube cookies")
        except Exception as e:
            print(f"ERROR: {e}")


if __name__ == "__main__":
    main()
